version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
  whisper:
    build: whisper
    ports:
      - 5000:5000
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./whisper:/app
    tmpfs:
      - /tmp
