version: '3'
volumes:
  redis-data:
  redis-insight-data:
  worker-data:
  open-webui-data:
services:
  app:
    build: .
    tty: true
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - worker-data:/tmp/worker
    env_file:
      - .env
    environment:
      WORKER_PATH: /tmp/worker
  worker_convert:
    build: .
    command: ['yarn', 'run', 'worker:convert']
    tty: true
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - worker-data:/tmp/worker
    tmpfs:
      - /tmp
    env_file:
      - .env
    environment:
      WORKER_PATH: /tmp/worker
  worker_transcribe:
    build: .
    command: ['yarn', 'run', 'worker:transcribe']
    tty: true
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - worker-data:/tmp/worker
    tmpfs:
      - /tmp
    env_file:
      - .env
    environment:
      WORKER_PATH: /tmp/worker
  whisper:
    build: whisper
    ports:
      - 5000:5000
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./whisper:/app
    tmpfs:
      - /tmp
    env_file:
      - .env
  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    security_opt:
      - seccomp:unconfined
    volumes:
      - redis-data:/data
  redis-ui:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redis-insight-data:/data
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 4000:8080
    volumes:
      - open-webui-data:/app/backend/data
    env_file:
      - .env
    environment:
      WEBUI_AUTH: 'False'
