version: '3'
volumes:
  redis-data:
  redis-insight-data:
  open-webui-data:
services:
  app:
    build: .
    tty: true
    depends_on:
      - redis
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    security_opt:
      - seccomp:unconfined
    volumes:
      - redis-data:/data
  redis-ui:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redis-insight-data:/data
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 4040:8080
    security_opt:
      - seccomp:unconfined
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      WEBUI_AUTH: 'False'
