name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/discord-extension

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: extensions/discord
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-server:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Trigger Webhooks
        run: |
          curl -X POST -H 'Content-Type: application-json' ${{ secrets.DEPLOY_WEBHOOK_URL }}

  deploy-functions:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          docker pull ghcr.io/${GITHUB_REPOSITORY,,}/discord-extension:main

      - name: Environment Variables
        run: |
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
          echo "S3_PREFIX=${{ secrets.S3_PREFIX }}" >> .env
          echo "SUBNET_IDS=${{ secrets.SUBNET_IDS }}" >> .env
          echo "SECURITY_GROUP_IDS=${{ secrets.SECURITY_GROUP_IDS }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=ap-northeast-1" >> .env

      - name: Build and Deploy
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          docker run --env-file .env ghcr.io/${GITHUB_REPOSITORY,,}/discord-extension:main ./deploy.sh
